Avoid unnecessary `git pull`
This causes an issue with the submodule during the GitHub Action workflow:

```
Fetching submodule scripts/inspector_protocol
error: RPC failed; HTTP 400 curl 22 The requested URL returned error: 400
fatal: error reading section header 'acknowledgments'
Errors during submodule fetch:
	scripts/inspector_protocol
Error: Process completed with exit code 1.
```

Issue: #266